apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs2
  labels:
    type: aws-ebs
spec:
  storageClassName: slow
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
  awsElasticBlockStore:
    volumeID: vol-0969a973ec12ff31d
    fsType: ext4
