apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs3
  labels:
    type: aws-ebs
spec:
  storageClassName: slow
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
  awsElasticBlockStore:
    volumeID: "vol-026b3fe8a5eec1074"
    fsType: ext4
