apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs-ch10data
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
  awsElasticBlockStore:
    volumeID: "vol-026b3fe8a5eec1074"
    fsType: ext4
