apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs1
  labels:
    type: aws-ebs
spec:
  storageClassName: slow
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
  awsElasticBlockStore:
    volumeID: "vol-0ffa3f46b40aba681"
    fsType: ext4
