apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
parameters:
  fsType: xfs
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
mountOptions:
  - rw
allowVolumeExpansion: false
#allowedTopologies:
#- matchLabelExpressions:
#  - key: failure-domain.beta.kubernetes.io/zone
#    values: 
#    - us-gov-west-1a
