apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/no-provisioner
parameters:
  fsType: xfs
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
mountOptions:
  - rw
allowVolumeExpansion: false
