apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio-node1-vol2
  labels:
    type: minio
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
  local:
    path: /minio-data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: label
          operator: In
          values:
          - tipdev-node1
