# This service has not been used yet.
apiVersion: v1
kind: Service
metadata:
  name: minio-ui-svc
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
  selector:
    app: minio

