apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ebs-ch10data
  namespace: tipapp
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeName: pvc-ebs-ch10data
