apiVersion: apps/v1
kind: Deployment
metadata:
  name: tip-app-deployment
  namespace: tipapp
  labels:
    app: tipapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tipapp
  template:
    metadata:
      labels:
        app: tipapp
    spec:
      restartPolicy: Always
      volumes:
      - name: tipapp-data
        emptyDir: {}
      containers:
      - name: tipfe
        image: registry.il2.dsop.io/skicamp/project-opal/tip-front-end:3d522f91
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: tipapp-data
          mountPath: /usr/src/app/uploads
        env: 
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-keys-secret
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-keys-secret
              key: minio-secret-key
      - name: tipbe
        image: registry.il2.dsop.io/skicamp/project-opal/tip-front-end:tipbe4
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: tipapp-data
          mountPath: /data
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-keys-secret
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-keys-secret
              key: minio-secret-key
      - name: nats
        image: nats:linux
        imagePullPolicy: IfNotPresent
        ports:
        # Expose on pod for debug, should be able to send messages.
        - containerPort: 4222
        args:
        - "-DV"
      imagePullSecrets:
      - name: regcred
