# http://<master node IP addr>:3000 
apiVersion: v1
kind: Service
metadata:
  name: tipapp-ui-svc
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort:30000
  selector:
    app: tipapp
